### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by micopa** [UniLuFS2020-ReplicationSeminar/Data_Mining_EX2#1]
Do you guys know why changing the date in the search (code) doesn't matter? It always just shows articles in 2022 and 2023. 
And maybe using tags instead of content could provide us more relevant articles? 

https://open-platform.theguardian.com/documentation/

**Comment by patrick-stoeckli** [comment]
fyi. i closed this issue because i replaced the custom-made wrapper function with a function from the package guardianapi and it actually worked.
