### ISSUE TITLE
Application of choice

### ISSUE THREAD

**Issue by patrick-stoeckli** [UniLuFS2020-ReplicationSeminar/Data_Mining_EX2#2]
What application of choice should we do?

I suggest that two of us make a short sentiment analysis of one of the topics and a third makes a plot that summarizes the findings.

What are your ideas?

**Comment by micopa** [comment]
I have now tried to create a graph showing the amount of times "solar energy" comes up but there weren't any findings. But yes a sentiment analysis would be great.

**Comment by patrick-stoeckli** [comment]
regarding 1) yes, i agree.

regarding 2) done (see pull request). please note that it takes "a while" (15-20 minutes) to get the new data. maybe it would make sense to push it to github as well?

**Comment by tobiasuruali** [comment]
I tried to add the dataset, but my LFS storage is already close to full. But when I ran the script it took me not more than 5minutes to scrape all the articles. That should be conceivable

**Comment by tobiasuruali** [comment]
Finalized this with Pull Request. Fixed #8
