### ISSUE TITLE
Code commenting and Variable Names 

### ISSUE THREAD

**Issue by tobiasuruali** [UniLuFS2020-ReplicationSeminar/Data_Mining_EX2#3]
Hey guys, 

I've noticed that our code seems to have quite a few sections where code snippets don't have a lot of comments explaining what's happening.  
Could you please add some comments explaining your code. Additionally adding some descriptive variables. 

https://github.com/UniLuFS2020-ReplicationSeminar/Data_Mining_EX2/blob/250117a99fb577ad1dd3898ce5271d2b6bb4bb5a/code/00_example_scrape_articles.R

https://github.com/UniLuFS2020-ReplicationSeminar/Data_Mining_EX2/blob/250117a99fb577ad1dd3898ce5271d2b6bb4bb5a/code/01_data_evaluation.R

**Comment by patrick-stoeckli** [comment]
done, at least in the scrape code, see the newest pull request.
